# SPDX-FileCopyrightText: 2019 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: MPL-2.0

steps:
  - command: nix run  -f $(nix eval --raw '((import ./nix/sources.nix).nixpkgs)') nixFlakes -c nix --experimental-features "nix-command nix-flakes" flake check
    label: Library and tests
    - command: nix run -f $(nix eval --raw '((import ./nix/sources.nix).nixpkgs)') -c nix --experimental-features "nix-command nix-flakes"  build
    label: Executable
    artifact_paths:
      - "result/bin/xrefcheck"
  - command: nix run -f. -c xrefcheck
    label: Xrefcheck itself
  - command: nix run -f $(nix eval --raw '((import ./nix/sources.nix).nixpkgs)') reuse -c reuse lint
    label: REUSE lint
  - command:
      - NIX_PATH=nixpkgs=$(nix eval --raw '(import ./nix/sources.nix).nixpkgs') nix-shell -p curl git gitAndTools.hub --run "curl https://raw.githubusercontent.com/serokell/scratch/release-binary/scripts/release-binary.sh | bash"
    label: Create a pre-release
    branches: master
